

apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure-container
        image: gems070903/myproject0:2
        ports:
        - containerPort: 8080
        
